/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.49.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};

/// struct for passing parameters to the method [`rest_private_slash_create_bot`]
#[derive(Clone, Debug)]
pub struct RestPrivateSlashCreateBotParams {
    pub rest_private_create_bot_request: Option<models::RestPrivateCreateBotRequest>
}


/// struct for typed errors of method [`rest_private_slash_bots`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RestPrivateSlashBotsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`rest_private_slash_create_bot`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RestPrivateSlashCreateBotError {
    UnknownValue(serde_json::Value),
}


/// Exchange: `https://thalex.com/api/v2/private/bots`  Testnet: `https://testnet.thalex.com/api/v2/private/bots`  Get bots
pub fn rest_private_slash_bots(configuration: &configuration::Configuration) -> Result<models::RestPrivateBots200Response, Error<RestPrivateSlashBotsError>> {

    let uri_str = format!("{}/private/bots", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req)?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text()?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::RestPrivateBots200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::RestPrivateBots200Response`")))),
        }
    } else {
        let content = resp.text()?;
        let entity: Option<RestPrivateSlashBotsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Exchange: `https://thalex.com/api/v2/private/create_bot`  Testnet: `https://testnet.thalex.com/api/v2/private/create_bot`  Instantiate a bot that keeps continually trading in your name according to a predefined strategy. See [the bot strategies section](#tag/bot_strategies) for more info on bots. For risk fencing reasons and because of the complex ways manual trades can interact with bot strategies, you might want to consider running bots on a separate/dedicated sub account. Also be aware that you can set up bots with different strategies in a way that they would end up trading with each other. 
pub fn rest_private_slash_create_bot(configuration: &configuration::Configuration, params: RestPrivateSlashCreateBotParams) -> Result<models::RestPrivateCreateBot200Response, Error<RestPrivateSlashCreateBotError>> {

    let uri_str = format!("{}/private/create_bot", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&params.rest_private_create_bot_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req)?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text()?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::RestPrivateCreateBot200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::RestPrivateCreateBot200Response`")))),
        }
    } else {
        let content = resp.text()?;
        let entity: Option<RestPrivateSlashCreateBotError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

