/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.49.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};

/// struct for passing parameters to the method [`rest_private_slash_create_conditional_order`]
#[derive(Clone, Debug)]
pub struct RestPrivateSlashCreateConditionalOrderParams {
    pub rest_private_create_conditional_order_request: Option<models::RestPrivateCreateConditionalOrderRequest>
}


/// struct for typed errors of method [`rest_private_slash_conditional_orders`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RestPrivateSlashConditionalOrdersError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`rest_private_slash_create_conditional_order`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RestPrivateSlashCreateConditionalOrderError {
    UnknownValue(serde_json::Value),
}


/// Exchange: `https://thalex.com/api/v2/private/conditional_orders`  Testnet: `https://testnet.thalex.com/api/v2/private/conditional_orders`  Get conditional orders
pub fn rest_private_slash_conditional_orders(configuration: &configuration::Configuration) -> Result<models::RestPrivateConditionalOrders200Response, Error<RestPrivateSlashConditionalOrdersError>> {

    let uri_str = format!("{}/private/conditional_orders", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req)?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text()?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::RestPrivateConditionalOrders200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::RestPrivateConditionalOrders200Response`")))),
        }
    } else {
        let content = resp.text()?;
        let entity: Option<RestPrivateSlashConditionalOrdersError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Exchange: `https://thalex.com/api/v2/private/create_conditional_order`  Testnet: `https://testnet.thalex.com/api/v2/private/create_conditional_order`  A buy order will activate when a trade/mark/index happens at a price at or higher than the stop price, or at or lower than the bracket price (if set). A sell order will activate when a trigger happens at a price at or lower than the stop price, or at or higher than the bracket price (if set).  When a callback rate is set, the stop price for a buy order will trail down at (trade price * (1 + callback rate)), and for a sell order the stop price will trail up at (trade price * (1 - callback rate)).  A stop limit order will activate to a good-till-cancelled limit order, all other types will activate to a market order.  The `last` trigger target tracks aggressive trades in the instrument. The `mark` target tracks the mark price of the instrument, as calculated every second by the Thalex pricing engine. The `index` trigger target is allowed only for futures (instrument type `perpetual` or `future`), and tracks the index price of the respective underlying, as calculated every second by the Thalex pricing engine.  Only the following combinations are possible:  * stop order: set only stop price * stop limit order: set stop price and limit price * bracket order: set stop price and bracket price. For a buy order, the bracket price must be under the stop price, and   for a sell order the other way around. * trailing stop loss order: set stop price and callback rate. 
pub fn rest_private_slash_create_conditional_order(configuration: &configuration::Configuration, params: RestPrivateSlashCreateConditionalOrderParams) -> Result<models::RestPrivateCreateConditionalOrder200Response, Error<RestPrivateSlashCreateConditionalOrderError>> {

    let uri_str = format!("{}/private/create_conditional_order", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&params.rest_private_create_conditional_order_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req)?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text()?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::RestPrivateCreateConditionalOrder200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::RestPrivateCreateConditionalOrder200Response`")))),
        }
    } else {
        let content = resp.text()?;
        let entity: Option<RestPrivateSlashCreateConditionalOrderError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

