/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.49.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};

/// struct for passing parameters to the method [`rest_public_slash_index_price_historical_data`]
#[derive(Clone, Debug)]
pub struct RestPublicSlashIndexPriceHistoricalDataParams {
    pub index_name: String,
    pub from: f64,
    pub to: f64,
    pub resolution: String
}

/// struct for passing parameters to the method [`rest_public_slash_mark_price_historical_data`]
#[derive(Clone, Debug)]
pub struct RestPublicSlashMarkPriceHistoricalDataParams {
    pub instrument_name: String,
    pub from: f64,
    pub to: f64,
    pub resolution: String
}


/// struct for typed errors of method [`rest_public_slash_index_price_historical_data`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RestPublicSlashIndexPriceHistoricalDataError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`rest_public_slash_mark_price_historical_data`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RestPublicSlashMarkPriceHistoricalDataError {
    UnknownValue(serde_json::Value),
}


/// Exchange: `https://thalex.com/api/v2/public/index_price_historical_data`  Testnet: `https://testnet.thalex.com/api/v2/public/index_price_historical_data`  Returns index price historical data in the specified interval and resolution in OHLC format.
pub fn rest_public_slash_index_price_historical_data(configuration: &configuration::Configuration, params: RestPublicSlashIndexPriceHistoricalDataParams) -> Result<models::RestPublicIndexPriceHistoricalData200Response, Error<RestPublicSlashIndexPriceHistoricalDataError>> {

    let uri_str = format!("{}/public/index_price_historical_data", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("index_name", &params.index_name.to_string())]);
    req_builder = req_builder.query(&[("from", &params.from.to_string())]);
    req_builder = req_builder.query(&[("to", &params.to.to_string())]);
    req_builder = req_builder.query(&[("resolution", &params.resolution.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req)?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text()?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::RestPublicIndexPriceHistoricalData200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::RestPublicIndexPriceHistoricalData200Response`")))),
        }
    } else {
        let content = resp.text()?;
        let entity: Option<RestPublicSlashIndexPriceHistoricalDataError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Exchange: `https://thalex.com/api/v2/public/mark_price_historical_data`  Testnet: `https://testnet.thalex.com/api/v2/public/mark_price_historical_data`  Returns mark price historical data in the specified interval and resolution in OHLC format.
pub fn rest_public_slash_mark_price_historical_data(configuration: &configuration::Configuration, params: RestPublicSlashMarkPriceHistoricalDataParams) -> Result<models::RestPublicMarkPriceHistoricalData200Response, Error<RestPublicSlashMarkPriceHistoricalDataError>> {

    let uri_str = format!("{}/public/mark_price_historical_data", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("instrument_name", &params.instrument_name.to_string())]);
    req_builder = req_builder.query(&[("from", &params.from.to_string())]);
    req_builder = req_builder.query(&[("to", &params.to.to_string())]);
    req_builder = req_builder.query(&[("resolution", &params.resolution.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req)?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text()?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::RestPublicMarkPriceHistoricalData200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::RestPublicMarkPriceHistoricalData200Response`")))),
        }
    } else {
        let content = resp.text()?;
        let entity: Option<RestPublicSlashMarkPriceHistoricalDataError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

