/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.49.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};

/// struct for passing parameters to the method [`rest_private_slash_notifications_inbox`]
#[derive(Clone, Debug)]
pub struct RestPrivateSlashNotificationsInboxParams {
    pub limit: Option<i32>
}


/// struct for typed errors of method [`rest_private_slash_notifications_inbox`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RestPrivateSlashNotificationsInboxError {
    UnknownValue(serde_json::Value),
}


/// Exchange: `https://thalex.com/api/v2/private/notifications_inbox`  Testnet: `https://testnet.thalex.com/api/v2/private/notifications_inbox`  This method returns a list of latest notifications that were sent to the current user. The list only contains items for which the `inbox` preference is set` (either in user preferences, or by default). 
pub fn rest_private_slash_notifications_inbox(configuration: &configuration::Configuration, params: RestPrivateSlashNotificationsInboxParams) -> Result<models::RestPrivateNotificationsInbox200Response, Error<RestPrivateSlashNotificationsInboxError>> {

    let uri_str = format!("{}/private/notifications_inbox", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req)?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text()?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::RestPrivateNotificationsInbox200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::RestPrivateNotificationsInbox200Response`")))),
        }
    } else {
        let content = resp.text()?;
        let entity: Option<RestPrivateSlashNotificationsInboxError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

