/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.49.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};

/// struct for passing parameters to the method [`rest_private_slash_mm_rfq_amend_quote`]
#[derive(Clone, Debug)]
pub struct RestPrivateSlashMmRfqAmendQuoteParams {
    pub rest_private_mm_rfq_amend_quote_request: Option<models::RestPrivateMmRfqAmendQuoteRequest>
}

/// struct for passing parameters to the method [`rest_private_slash_mm_rfq_insert_quote`]
#[derive(Clone, Debug)]
pub struct RestPrivateSlashMmRfqInsertQuoteParams {
    pub rest_private_mm_rfq_insert_quote_request: Option<models::RestPrivateMmRfqInsertQuoteRequest>
}


/// struct for typed errors of method [`rest_private_slash_mm_rfq_amend_quote`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RestPrivateSlashMmRfqAmendQuoteError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`rest_private_slash_mm_rfq_insert_quote`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RestPrivateSlashMmRfqInsertQuoteError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`rest_private_slash_mm_rfq_quotes`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RestPrivateSlashMmRfqQuotesError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`rest_private_slash_mm_rfqs`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RestPrivateSlashMmRfqsError {
    UnknownValue(serde_json::Value),
}


/// Exchange: `https://thalex.com/api/v2/private/mm_rfq_amend_quote`  Testnet: `https://testnet.thalex.com/api/v2/private/mm_rfq_amend_quote`  Change the amount and price of an existing quote. 
pub fn rest_private_slash_mm_rfq_amend_quote(configuration: &configuration::Configuration, params: RestPrivateSlashMmRfqAmendQuoteParams) -> Result<models::RestPrivateMmRfqInsertQuote200Response, Error<RestPrivateSlashMmRfqAmendQuoteError>> {

    let uri_str = format!("{}/private/mm_rfq_amend_quote", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&params.rest_private_mm_rfq_amend_quote_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req)?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text()?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::RestPrivateMmRfqInsertQuote200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::RestPrivateMmRfqInsertQuote200Response`")))),
        }
    } else {
        let content = resp.text()?;
        let entity: Option<RestPrivateSlashMmRfqAmendQuoteError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Exchange: `https://thalex.com/api/v2/private/mm_rfq_insert_quote`  Testnet: `https://testnet.thalex.com/api/v2/private/mm_rfq_insert_quote`  Sends a new quote on the indicated RFQ. This does *not* remove any previous quote: any number of quotes may be active on either side. Note that if the session was set to non-persistent (cancel-on-disconnect), then this quote will also be non-persistent. 
pub fn rest_private_slash_mm_rfq_insert_quote(configuration: &configuration::Configuration, params: RestPrivateSlashMmRfqInsertQuoteParams) -> Result<models::RestPrivateMmRfqInsertQuote200Response, Error<RestPrivateSlashMmRfqInsertQuoteError>> {

    let uri_str = format!("{}/private/mm_rfq_insert_quote", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&params.rest_private_mm_rfq_insert_quote_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req)?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text()?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::RestPrivateMmRfqInsertQuote200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::RestPrivateMmRfqInsertQuote200Response`")))),
        }
    } else {
        let content = resp.text()?;
        let entity: Option<RestPrivateSlashMmRfqInsertQuoteError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Exchange: `https://thalex.com/api/v2/private/mm_rfq_quotes`  Testnet: `https://testnet.thalex.com/api/v2/private/mm_rfq_quotes`  Retrieves a list of open RFQ quotes across all RFQs.
pub fn rest_private_slash_mm_rfq_quotes(configuration: &configuration::Configuration) -> Result<models::RestPrivateMmRfqQuotes200Response, Error<RestPrivateSlashMmRfqQuotesError>> {

    let uri_str = format!("{}/private/mm_rfq_quotes", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req)?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text()?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::RestPrivateMmRfqQuotes200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::RestPrivateMmRfqQuotes200Response`")))),
        }
    } else {
        let content = resp.text()?;
        let entity: Option<RestPrivateSlashMmRfqQuotesError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Exchange: `https://thalex.com/api/v2/private/mm_rfqs`  Testnet: `https://testnet.thalex.com/api/v2/private/mm_rfqs`  Retrieves a list of open RFQs that this account has access to.
pub fn rest_private_slash_mm_rfqs(configuration: &configuration::Configuration) -> Result<models::RestPrivateOpenRfqs200Response, Error<RestPrivateSlashMmRfqsError>> {

    let uri_str = format!("{}/private/mm_rfqs", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req)?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text()?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::RestPrivateOpenRfqs200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::RestPrivateOpenRfqs200Response`")))),
        }
    } else {
        let content = resp.text()?;
        let entity: Option<RestPrivateSlashMmRfqsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

