/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.49.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};

/// struct for passing parameters to the method [`rest_private_slash_create_rfq`]
#[derive(Clone, Debug)]
pub struct RestPrivateSlashCreateRfqParams {
    pub rest_private_create_rfq_request: Option<models::RestPrivateCreateRfqRequest>
}

/// struct for passing parameters to the method [`rest_private_slash_trade_rfq`]
#[derive(Clone, Debug)]
pub struct RestPrivateSlashTradeRfqParams {
    pub rest_private_trade_rfq_request: Option<models::RestPrivateTradeRfqRequest>
}


/// struct for typed errors of method [`rest_private_slash_create_rfq`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RestPrivateSlashCreateRfqError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`rest_private_slash_open_rfqs`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RestPrivateSlashOpenRfqsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`rest_private_slash_trade_rfq`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RestPrivateSlashTradeRfqError {
    UnknownValue(serde_json::Value),
}


/// Exchange: `https://thalex.com/api/v2/private/create_rfq`  Testnet: `https://testnet.thalex.com/api/v2/private/create_rfq`  Creates a new RFQ. You do not have to indicate upfront whether you want to buy or sell this package. Indicate the full size of the package. 
pub fn rest_private_slash_create_rfq(configuration: &configuration::Configuration, params: RestPrivateSlashCreateRfqParams) -> Result<models::RestPrivateCreateRfq200Response, Error<RestPrivateSlashCreateRfqError>> {

    let uri_str = format!("{}/private/create_rfq", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&params.rest_private_create_rfq_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req)?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text()?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::RestPrivateCreateRfq200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::RestPrivateCreateRfq200Response`")))),
        }
    } else {
        let content = resp.text()?;
        let entity: Option<RestPrivateSlashCreateRfqError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Exchange: `https://thalex.com/api/v2/private/open_rfqs`  Testnet: `https://testnet.thalex.com/api/v2/private/open_rfqs`  Retrieves a list of open RFQs created by this account.
pub fn rest_private_slash_open_rfqs(configuration: &configuration::Configuration) -> Result<models::RestPrivateOpenRfqs200Response, Error<RestPrivateSlashOpenRfqsError>> {

    let uri_str = format!("{}/private/open_rfqs", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req)?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text()?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::RestPrivateOpenRfqs200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::RestPrivateOpenRfqs200Response`")))),
        }
    } else {
        let content = resp.text()?;
        let entity: Option<RestPrivateSlashOpenRfqsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Exchange: `https://thalex.com/api/v2/private/trade_rfq`  Testnet: `https://testnet.thalex.com/api/v2/private/trade_rfq`  Trade on the quotes given. The requested amount is that of the original request. 
pub fn rest_private_slash_trade_rfq(configuration: &configuration::Configuration, params: RestPrivateSlashTradeRfqParams) -> Result<models::RestPrivateTradeRfq200Response, Error<RestPrivateSlashTradeRfqError>> {

    let uri_str = format!("{}/private/trade_rfq", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&params.rest_private_trade_rfq_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req)?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text()?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::RestPrivateTradeRfq200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::RestPrivateTradeRfq200Response`")))),
        }
    } else {
        let content = resp.text()?;
        let entity: Option<RestPrivateSlashTradeRfqError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

