/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.49.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Bot {
    Sgsl1(Box<models::Sgsl1>),
    Ocq1(Box<models::Ocq1>),
    Levels1(Box<models::Levels1>),
    Grid1(Box<models::Grid1>),
    DHedge1(Box<models::DHedge1>),
    DFollow1(Box<models::DFollow1>),
}

impl Default for Bot {
    fn default() -> Self {
        Self::Sgsl1(Default::default())
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Signal {
    #[serde(rename = "index")]
    Index,
    #[serde(rename = "mark")]
    Mark,
}

impl Default for Signal {
    fn default() -> Signal {
        Self::Index
    }
}

