/*
 * Websocket Subscription Schemas
 *
 * Schema definitions Websocket API subscriptions for Thalex exchange.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DeleteReasonEnum {
    #[serde(rename = "client_cancel")]
    ClientCancel,
    #[serde(rename = "session_end")]
    SessionEnd,
    #[serde(rename = "instrument_deactivated")]
    InstrumentDeactivated,
    #[serde(rename = "mm_protection")]
    MmProtection,
    #[serde(rename = "failover")]
    Failover,
    #[serde(rename = "margin_breach")]
    MarginBreach,
    #[serde(rename = "filled")]
    Filled,
}

impl std::fmt::Display for DeleteReasonEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::ClientCancel => write!(f, "client_cancel"),
            Self::SessionEnd => write!(f, "session_end"),
            Self::InstrumentDeactivated => write!(f, "instrument_deactivated"),
            Self::MmProtection => write!(f, "mm_protection"),
            Self::Failover => write!(f, "failover"),
            Self::MarginBreach => write!(f, "margin_breach"),
            Self::Filled => write!(f, "filled"),
        }
    }
}

impl Default for DeleteReasonEnum {
    fn default() -> DeleteReasonEnum {
        Self::ClientCancel
    }
}
