/*
 * Thalex RPC API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Deposit1 {
    /// The blockchain used for this transaction.
    #[serde(rename = "blockchain")]
    pub blockchain: String,
    /// The transaction hash.
    #[serde(rename = "transaction_hash")]
    pub transaction_hash: String,
}

impl Deposit1 {
    pub fn new(blockchain: String, transaction_hash: String) -> Deposit1 {
        Deposit1 {
            blockchain,
            transaction_hash,
        }
    }
}
