/*
 * Websocket Subscription Schemas
 *
 * Schema definitions Websocket API subscriptions for Thalex exchange.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EventEnum {
    #[serde(rename = "Inserted")]
    Inserted,
    #[serde(rename = "Amended")]
    Amended,
    #[serde(rename = "Cancelled")]
    Cancelled,
    #[serde(rename = "Filled")]
    Filled,
    #[serde(rename = "Existing")]
    Existing,
}

impl std::fmt::Display for EventEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Inserted => write!(f, "Inserted"),
            Self::Amended => write!(f, "Amended"),
            Self::Cancelled => write!(f, "Cancelled"),
            Self::Filled => write!(f, "Filled"),
            Self::Existing => write!(f, "Existing"),
        }
    }
}

impl Default for EventEnum {
    fn default() -> EventEnum {
        Self::Inserted
    }
}
