/*
 * Thalex RPC API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IndexPriceHistoricalDataParams {
    /// Index name (e.g. BTCUSD, ETHUSD).
    #[serde(rename = "index_name")]
    pub index_name: String,
    /// Start time (Unix timestamp).
    #[serde(rename = "from")]
    pub from: f64,
    /// End time (Unix timestamp) (exclusive).
    #[serde(rename = "to")]
    pub to: f64,
    /// Each data point will be aggregated using OHLC according to the specified resolution.
    #[serde(rename = "resolution")]
    pub resolution: Resolution,
}

impl IndexPriceHistoricalDataParams {
    pub fn new(
        index_name: String,
        from: f64,
        to: f64,
        resolution: Resolution,
    ) -> IndexPriceHistoricalDataParams {
        IndexPriceHistoricalDataParams {
            index_name,
            from,
            to,
            resolution,
        }
    }
}
/// Each data point will be aggregated using OHLC according to the specified resolution.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Resolution {
    #[serde(rename = "1m")]
    Variant1m,
    #[serde(rename = "5m")]
    Variant5m,
    #[serde(rename = "15m")]
    Variant15m,
    #[serde(rename = "30m")]
    Variant30m,
    #[serde(rename = "1h")]
    Variant1h,
    #[serde(rename = "1d")]
    Variant1d,
    #[serde(rename = "1w")]
    Variant1w,
}

impl Default for Resolution {
    fn default() -> Resolution {
        Self::Variant1m
    }
}
