/*
 * Websocket Subscription Schemas
 *
 * Schema definitions Websocket API subscriptions for Thalex exchange.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InstrumentDeltaOneOf1 {
    #[serde(rename = "added", skip_serializing_if = "Option::is_none")]
    pub added: Option<models::Instrument>,
}

impl InstrumentDeltaOneOf1 {
    pub fn new() -> InstrumentDeltaOneOf1 {
        InstrumentDeltaOneOf1 { added: None }
    }
}
