/*
 * Websocket Subscription Schemas
 *
 * Schema definitions Websocket API subscriptions for Thalex exchange.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum InstrumentDelta {
    Added { added: models::Instrument },
    Removed { removed: models::Instrument },
}

impl Default for InstrumentDelta {
    fn default() -> Self {
        Self::Added {
            added: Default::default(),
        }
    }
}
