/*
 * Websocket Subscription Schemas
 *
 * Schema definitions Websocket API subscriptions for Thalex exchange.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InstrumentsNotification {
    #[serde(rename = "channel_name")]
    pub channel_name: String,
    #[serde(rename = "notification")]
    pub notification: Vec<models::InstrumentDelta>,
    #[serde(rename = "snapshot", skip_serializing_if = "Option::is_none")]
    pub snapshot: Option<bool>,
}

impl InstrumentsNotification {
    pub fn new(
        channel_name: String,
        notification: Vec<models::InstrumentDelta>,
    ) -> InstrumentsNotification {
        InstrumentsNotification {
            channel_name,
            notification,
            snapshot: None,
        }
    }
}
