/*
 * Thalex RPC API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InternalTransfer {
    /// Account number of the transfer destination.
    #[serde(rename = "to_account")]
    pub to_account: String,
    /// Account number of the transfer source.
    #[serde(rename = "from_account")]
    pub from_account: String,
}

impl InternalTransfer {
    pub fn new(to_account: String, from_account: String) -> InternalTransfer {
        InternalTransfer {
            to_account,
            from_account,
        }
    }
}
