/*
 * Thalex RPC API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MarginBreakdownWithOrder : Lightweight margin breakdown without and with an order inserted as buy or sell.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MarginBreakdownWithOrder {
    #[serde(rename = "current", skip_serializing_if = "Option::is_none")]
    pub current: Option<models::MarginBreakdownWithOrderCurrent>,
    #[serde(rename = "with_buy", skip_serializing_if = "Option::is_none")]
    pub with_buy: Option<models::MarginBreakdownWithOrderWithBuy>,
    #[serde(rename = "with_sell", skip_serializing_if = "Option::is_none")]
    pub with_sell: Option<models::MarginBreakdownWithOrderWithSell>,
}

impl MarginBreakdownWithOrder {
    /// Lightweight margin breakdown without and with an order inserted as buy or sell.
    pub fn new() -> MarginBreakdownWithOrder {
        MarginBreakdownWithOrder {
            current: None,
            with_buy: None,
            with_sell: None,
        }
    }
}
