/*
 * Thalex RPC API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MarketVelocityProgramPayment {
    /// Period end time (Unix timestamp)
    #[serde(rename = "period_start")]
    pub period_start: rust_decimal::Decimal,
}

impl MarketVelocityProgramPayment {
    pub fn new(period_start: rust_decimal::Decimal) -> MarketVelocityProgramPayment {
        MarketVelocityProgramPayment { period_start }
    }
}
