/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.49.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Notifications {
    /// List of notifications ordered from newest to oldest.
    #[serde(rename = "notifications", skip_serializing_if = "Option::is_none")]
    pub notifications: Option<Vec<models::NotificationsNotificationsInner>>,
}

impl Notifications {
    pub fn new() -> Notifications {
        Notifications {
            notifications: None,
        }
    }
}

