/*
 * Thalex RPC API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PerpetualDataPoint : A single OHLC data point with funding payment and top of book
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PerpetualDataPoint {
    /// Unix timestamp (seconds) of the start of the data point
    #[serde(rename = "timestamp")]
    pub timestamp: f64,
    /// Open (first) value of the interval
    #[serde(rename = "open")]
    pub open: f64,
    /// High (maximum) value of the interval
    #[serde(rename = "high")]
    pub high: f64,
    /// Low (minimum) value of the interval
    #[serde(rename = "low")]
    pub low: f64,
    /// Close (last) value of the interval
    #[serde(rename = "close")]
    pub close: f64,
    /// Funding payment during the interval
    #[serde(rename = "funding")]
    pub funding: f64,
    #[serde(
        rename = "topOfBook",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub top_of_book: Option<Option<models::TopOfBookPerpetual>>,
}

impl PerpetualDataPoint {
    /// A single OHLC data point with funding payment and top of book
    pub fn new(
        timestamp: f64,
        open: f64,
        high: f64,
        low: f64,
        close: f64,
        funding: f64,
    ) -> PerpetualDataPoint {
        PerpetualDataPoint {
            timestamp,
            open,
            high,
            low,
            close,
            funding,
            top_of_book: None,
        }
    }
}
