/*
 * Thalex RPC API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PerpetualMarkPriceHistoricalData : Array of PerpetualDataPoint objects
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PerpetualMarkPriceHistoricalData {}

impl PerpetualMarkPriceHistoricalData {
    /// Array of PerpetualDataPoint objects
    pub fn new() -> PerpetualMarkPriceHistoricalData {
        PerpetualMarkPriceHistoricalData {}
    }
}
