/*
 * Thalex RPC API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PortfolioMarginBreakdown : Required margin breakdown for accounts that use portfolio margin.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PortfolioMarginBreakdown {
    #[serde(rename = "portfolio", skip_serializing_if = "Option::is_none")]
    pub portfolio: Option<models::PortfolioMarginBreakdownPortfolio>,
}

impl PortfolioMarginBreakdown {
    /// Required margin breakdown for accounts that use portfolio margin.
    pub fn new() -> PortfolioMarginBreakdown {
        PortfolioMarginBreakdown { portfolio: None }
    }
}
