/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.49.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PrivateCancelRfq {
    PrivateRfqHistoryResult(Box<models::PrivateRfqHistoryResult>),
    PrivateTransactionHistoryResult(Box<models::PrivateTransactionHistoryResult>),
}

impl Default for PrivateCancelRfq {
    fn default() -> Self {
        Self::PrivateRfqHistoryResult(Default::default())
    }
}
