/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.49.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrivateRfqHistoryInlinePropertiesRfqsItemsPropertiesLegsItems {
    #[serde(rename = "instrument_name")]
    pub instrument_name: String,
    #[serde(rename = "quantity")]
    pub quantity: f64,
    #[serde(rename = "fee_quantity")]
    pub fee_quantity: f64,
}

impl PrivateRfqHistoryInlinePropertiesRfqsItemsPropertiesLegsItems {
    pub fn new(
        instrument_name: String,
        quantity: f64,
        fee_quantity: f64,
    ) -> PrivateRfqHistoryInlinePropertiesRfqsItemsPropertiesLegsItems {
        PrivateRfqHistoryInlinePropertiesRfqsItemsPropertiesLegsItems {
            instrument_name,
            quantity,
            fee_quantity,
        }
    }
}
