/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.49.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PrivateBots {
    PrivateBotsResult(Vec<models::Bot>),
    OrderFill(Box<models::OrderFill>),
}

impl Default for PrivateBots {
    fn default() -> Self {
        Self::PrivateBotsResult(Default::default())
    }
}
/// Maker (trade on book order) or taker (trade on new order), if applicable.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MakerTaker {
    #[serde(rename = "maker")]
    Maker,
    #[serde(rename = "taker")]
    Taker,
}

impl Default for MakerTaker {
    fn default() -> MakerTaker {
        Self::Maker
    }
}
