/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.49.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrivateBotsInlineItemsOneof4 {
    #[serde(rename = "strategy")]
    pub strategy: String,
    #[serde(rename = "instrument_name")]
    pub instrument_name: String,
    #[serde(rename = "position", skip_serializing_if = "Option::is_none")]
    pub position: Option<String>,
    #[serde(rename = "target_delta")]
    pub target_delta: f64,
    #[serde(rename = "threshold")]
    pub threshold: f64,
    #[serde(rename = "period")]
    pub period: f64,
    #[serde(rename = "max_slippage", skip_serializing_if = "Option::is_none")]
    pub max_slippage: Option<f64>,
    #[serde(rename = "end_time", skip_serializing_if = "Option::is_none")]
    pub end_time: Option<f64>,
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
}

impl PrivateBotsInlineItemsOneof4 {
    pub fn new(
        strategy: String,
        instrument_name: String,
        target_delta: f64,
        threshold: f64,
        period: f64,
    ) -> PrivateBotsInlineItemsOneof4 {
        PrivateBotsInlineItemsOneof4 {
            strategy,
            instrument_name,
            position: None,
            target_delta,
            threshold,
            period,
            max_slippage: None,
            end_time: None,
            label: None,
        }
    }
}
