/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.49.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrivateBotsInlineItemsOneof3 {
    #[serde(rename = "bot_id")]
    pub bot_id: String,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "stop_reason", skip_serializing_if = "Option::is_none")]
    pub stop_reason: Option<String>,
    #[serde(rename = "strategy")]
    pub strategy: String,
    #[serde(rename = "instrument_name")]
    pub instrument_name: String,
    #[serde(rename = "grid")]
    pub grid: Vec<f64>,
    #[serde(rename = "step_size")]
    pub step_size: f64,
    #[serde(rename = "base_position")]
    pub base_position: f64,
    #[serde(rename = "upside_exit_price")]
    pub upside_exit_price: f64,
    #[serde(rename = "downside_exit_price")]
    pub downside_exit_price: f64,
    #[serde(rename = "max_slippage", skip_serializing_if = "Option::is_none")]
    pub max_slippage: Option<f64>,
    #[serde(rename = "end_time")]
    pub end_time: f64,
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
}

impl PrivateBotsInlineItemsOneof3 {
    pub fn new(
        bot_id: String,
        status: String,
        strategy: String,
        instrument_name: String,
        grid: Vec<f64>,
        step_size: f64,
        base_position: f64,
        upside_exit_price: f64,
        downside_exit_price: f64,
        end_time: f64,
    ) -> PrivateBotsInlineItemsOneof3 {
        PrivateBotsInlineItemsOneof3 {
            bot_id,
            status,
            stop_reason: None,
            strategy,
            instrument_name,
            grid,
            step_size,
            base_position,
            upside_exit_price,
            downside_exit_price,
            max_slippage: None,
            end_time,
            label: None,
        }
    }
}
