/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.49.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrivateRequiredMarginBreakdownInlinePropertiesPortfolioPropertiesUnderlyingsItemsScenariosInner {
    #[serde(rename = "underlying_change_pct", skip_serializing_if = "Option::is_none")]
    pub underlying_change_pct: Option<f64>,
    #[serde(rename = "vol_change_pct_point", skip_serializing_if = "Option::is_none")]
    pub vol_change_pct_point: Option<f64>,
    #[serde(rename = "pnl", skip_serializing_if = "Option::is_none")]
    pub pnl: Option<f64>,
    #[serde(rename = "coverage_factor", skip_serializing_if = "Option::is_none")]
    pub coverage_factor: Option<f64>,
    #[serde(rename = "required_margin", skip_serializing_if = "Option::is_none")]
    pub required_margin: Option<f64>,
    #[serde(rename = "loss_margin", skip_serializing_if = "Option::is_none")]
    pub loss_margin: Option<f64>,
    #[serde(rename = "roll_cash_position", skip_serializing_if = "Option::is_none")]
    pub roll_cash_position: Option<f64>,
    #[serde(rename = "roll_contingency_margin", skip_serializing_if = "Option::is_none")]
    pub roll_contingency_margin: Option<f64>,
    #[serde(rename = "d1_roll_cash_position", skip_serializing_if = "Option::is_none")]
    pub d1_roll_cash_position: Option<f64>,
    #[serde(rename = "d1_roll_contingency_margin", skip_serializing_if = "Option::is_none")]
    pub d1_roll_contingency_margin: Option<f64>,
    #[serde(rename = "options_roll_cash_position", skip_serializing_if = "Option::is_none")]
    pub options_roll_cash_position: Option<f64>,
    #[serde(rename = "options_roll_contingency_margin", skip_serializing_if = "Option::is_none")]
    pub options_roll_contingency_margin: Option<f64>,
    #[serde(rename = "options_short_cash_position", skip_serializing_if = "Option::is_none")]
    pub options_short_cash_position: Option<f64>,
    #[serde(rename = "options_contingency_margin", skip_serializing_if = "Option::is_none")]
    pub options_contingency_margin: Option<f64>,
    #[serde(rename = "positions", skip_serializing_if = "Option::is_none")]
    pub positions: Option<Vec<models::PrivateRequiredMarginBreakdownInlinePropertiesPortfolioPropertiesUnderlyingsItemsScenariosInnerPositionsInner>>,
    #[serde(rename = "assets", skip_serializing_if = "Option::is_none")]
    pub assets: Option<Vec<models::PrivateRequiredMarginBreakdownInlinePropertiesPortfolioPropertiesUnderlyingsItemsScenariosInnerAssetsInner>>,
    #[serde(rename = "highlight", skip_serializing_if = "Option::is_none")]
    pub highlight: Option<bool>,
}

impl
    PrivateRequiredMarginBreakdownInlinePropertiesPortfolioPropertiesUnderlyingsItemsScenariosInner
{
    pub fn new() -> PrivateRequiredMarginBreakdownInlinePropertiesPortfolioPropertiesUnderlyingsItemsScenariosInner{
        PrivateRequiredMarginBreakdownInlinePropertiesPortfolioPropertiesUnderlyingsItemsScenariosInner {
            underlying_change_pct: None,
            vol_change_pct_point: None,
            pnl: None,
            coverage_factor: None,
            required_margin: None,
            loss_margin: None,
            roll_cash_position: None,
            roll_contingency_margin: None,
            d1_roll_cash_position: None,
            d1_roll_contingency_margin: None,
            options_roll_cash_position: None,
            options_roll_contingency_margin: None,
            options_short_cash_position: None,
            options_contingency_margin: None,
            positions: None,
            assets: None,
            highlight: None,
        }
    }
}
