/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.49.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrivateOrderHistoryInlinePropertiesOrdersItems {
    #[serde(rename = "order_id")]
    pub order_id: String,
    #[serde(rename = "order_type")]
    pub order_type: OrderType,
    #[serde(rename = "instrument_name", skip_serializing_if = "Option::is_none")]
    pub instrument_name: Option<String>,
    #[serde(rename = "legs", skip_serializing_if = "Option::is_none")]
    pub legs: Option<Vec<models::PrivateOrderHistoryInlinePropertiesOrdersItemsLegsInner>>,
    #[serde(rename = "direction")]
    pub direction: Direction,
    #[serde(rename = "price", skip_serializing_if = "Option::is_none")]
    pub price: Option<f64>,
    #[serde(rename = "amount")]
    pub amount: f64,
    #[serde(rename = "filled_amount")]
    pub filled_amount: f64,
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[serde(rename = "client_order_id", skip_serializing_if = "Option::is_none")]
    pub client_order_id: Option<f64>,
    #[serde(rename = "status")]
    pub status: Status,
    #[serde(rename = "fills")]
    pub fills: Vec<models::PrivateOrderHistoryInlinePropertiesOrdersItemsFillsInner>,
    #[serde(rename = "delete_reason")]
    pub delete_reason: DeleteReason,
    #[serde(rename = "insert_reason")]
    pub insert_reason: InsertReason,
    #[serde(
        rename = "conditional_order_id",
        skip_serializing_if = "Option::is_none"
    )]
    pub conditional_order_id: Option<String>,
    #[serde(rename = "bot_id", skip_serializing_if = "Option::is_none")]
    pub bot_id: Option<String>,
    #[serde(rename = "create_time")]
    pub create_time: f64,
    #[serde(rename = "close_time")]
    pub close_time: f64,
    #[serde(rename = "reduce_only", skip_serializing_if = "Option::is_none")]
    pub reduce_only: Option<bool>,
}

impl PrivateOrderHistoryInlinePropertiesOrdersItems {
    pub fn new(
        order_id: String,
        order_type: OrderType,
        direction: Direction,
        amount: f64,
        filled_amount: f64,
        status: Status,
        fills: Vec<models::PrivateOrderHistoryInlinePropertiesOrdersItemsFillsInner>,
        delete_reason: DeleteReason,
        insert_reason: InsertReason,
        create_time: f64,
        close_time: f64,
    ) -> PrivateOrderHistoryInlinePropertiesOrdersItems {
        PrivateOrderHistoryInlinePropertiesOrdersItems {
            order_id,
            order_type,
            instrument_name: None,
            legs: None,
            direction,
            price: None,
            amount,
            filled_amount,
            label: None,
            client_order_id: None,
            status,
            fills,
            delete_reason,
            insert_reason,
            conditional_order_id: None,
            bot_id: None,
            create_time,
            close_time,
            reduce_only: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OrderType {
    #[serde(rename = "limit")]
    Limit,
    #[serde(rename = "market")]
    Market,
}

impl Default for OrderType {
    fn default() -> OrderType {
        Self::Limit
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Direction {
    #[serde(rename = "buy")]
    Buy,
    #[serde(rename = "sell")]
    Sell,
}

impl Default for Direction {
    fn default() -> Direction {
        Self::Buy
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "open")]
    Open,
    #[serde(rename = "partially_filled")]
    PartiallyFilled,
    #[serde(rename = "cancelled")]
    Cancelled,
    #[serde(rename = "cancelled_partially_filled")]
    CancelledPartiallyFilled,
    #[serde(rename = "filled")]
    Filled,
}

impl Default for Status {
    fn default() -> Status {
        Self::Open
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DeleteReason {
    #[serde(rename = "client_cancel")]
    ClientCancel,
    #[serde(rename = "client_bulk_cancel")]
    ClientBulkCancel,
    #[serde(rename = "session_end")]
    SessionEnd,
    #[serde(rename = "instrument_deactivated")]
    InstrumentDeactivated,
    #[serde(rename = "mm_protection")]
    MmProtection,
    #[serde(rename = "failover")]
    Failover,
    #[serde(rename = "margin_breach")]
    MarginBreach,
    #[serde(rename = "filled")]
    Filled,
    #[serde(rename = "immediate_cancel")]
    ImmediateCancel,
    #[serde(rename = "admin_cancel")]
    AdminCancel,
}

impl Default for DeleteReason {
    fn default() -> DeleteReason {
        Self::ClientCancel
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum InsertReason {
    #[serde(rename = "client_request")]
    ClientRequest,
    #[serde(rename = "conditional_order")]
    ConditionalOrder,
    #[serde(rename = "liquidation")]
    Liquidation,
}

impl Default for InsertReason {
    fn default() -> InsertReason {
        Self::ClientRequest
    }
}
