/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.49.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PrivateBtcDepositAddress {
    PrivateBtcDepositAddressResult(String),
    ErrorResponse(Box<models::ErrorResponse>),
}

impl Default for PrivateBtcDepositAddress {
    fn default() -> Self {
        Self::PrivateBtcDepositAddressResult(Default::default())
    }
}
