/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.49.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrivateOrderHistoryInlinePropertiesOrdersItemsPropertiesLegsItems {
    #[serde(rename = "instrument_name")]
    pub instrument_name: String,
    #[serde(rename = "quantity")]
    pub quantity: f64,
    #[serde(rename = "filled_amount")]
    pub filled_amount: f64,
}

impl PrivateOrderHistoryInlinePropertiesOrdersItemsPropertiesLegsItems {
    pub fn new(
        instrument_name: String,
        quantity: f64,
        filled_amount: f64,
    ) -> PrivateOrderHistoryInlinePropertiesOrdersItemsPropertiesLegsItems {
        PrivateOrderHistoryInlinePropertiesOrdersItemsPropertiesLegsItems {
            instrument_name,
            quantity,
            filled_amount,
        }
    }
}
