/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.49.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrivateOrderHistoryInlinePropertiesOrdersItemsFillsInner {
    #[serde(rename = "trade_id")]
    pub trade_id: String,
    #[serde(rename = "price")]
    pub price: f64,
    #[serde(rename = "amount")]
    pub amount: f64,
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<f64>,
    #[serde(rename = "maker_taker")]
    pub maker_taker: MakerTaker,
    #[serde(rename = "leg_index")]
    pub leg_index: f64,
}

impl PrivateOrderHistoryInlinePropertiesOrdersItemsFillsInner {
    pub fn new(
        trade_id: String,
        price: f64,
        amount: f64,
        maker_taker: MakerTaker,
        leg_index: f64,
    ) -> PrivateOrderHistoryInlinePropertiesOrdersItemsFillsInner {
        PrivateOrderHistoryInlinePropertiesOrdersItemsFillsInner {
            trade_id,
            price,
            amount,
            time: None,
            maker_taker,
            leg_index,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MakerTaker {
    #[serde(rename = "maker")]
    Maker,
    #[serde(rename = "taker")]
    Taker,
}

impl Default for MakerTaker {
    fn default() -> MakerTaker {
        Self::Maker
    }
}
