/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.49.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrivateBotsInlineItemsOneof5 {
    #[serde(rename = "strategy")]
    pub strategy: String,
    #[serde(rename = "instrument_name")]
    pub instrument_name: String,
    #[serde(rename = "target_instrument")]
    pub target_instrument: String,
    #[serde(rename = "target_amount")]
    pub target_amount: f64,
    #[serde(rename = "threshold")]
    pub threshold: f64,
    #[serde(rename = "period")]
    pub period: f64,
    #[serde(rename = "max_slippage", skip_serializing_if = "Option::is_none")]
    pub max_slippage: Option<f64>,
    #[serde(rename = "end_time")]
    pub end_time: f64,
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
}

impl PrivateBotsInlineItemsOneof5 {
    pub fn new(
        strategy: String,
        instrument_name: String,
        target_instrument: String,
        target_amount: f64,
        threshold: f64,
        period: f64,
        end_time: f64,
    ) -> PrivateBotsInlineItemsOneof5 {
        PrivateBotsInlineItemsOneof5 {
            strategy,
            instrument_name,
            target_instrument,
            target_amount,
            threshold,
            period,
            max_slippage: None,
            end_time,
            label: None,
        }
    }
}
