/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.49.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PrivateWithdraw {
    PrivateCancelAllResult(f64),
    PublicInstrumentsResult(Vec<models::Instrument>),
}

impl Default for PrivateWithdraw {
    fn default() -> Self {
        Self::PrivateCancelAllResult(Default::default())
    }
}
