/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.49.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrivateBotsInlineItemsOneof2 {
    #[serde(rename = "bot_id")]
    pub bot_id: String,
    #[serde(rename = "status")]
    pub status: Status,
    #[serde(rename = "stop_reason", skip_serializing_if = "Option::is_none")]
    pub stop_reason: Option<String>,
    #[serde(rename = "strategy")]
    pub strategy: String,
    #[serde(rename = "instrument_name")]
    pub instrument_name: String,
    #[serde(rename = "bids")]
    pub bids: Vec<f64>,
    #[serde(rename = "asks")]
    pub asks: Vec<f64>,
    #[serde(rename = "step_size")]
    pub step_size: f64,
    #[serde(rename = "base_position")]
    pub base_position: f64,
    #[serde(rename = "upside_exit_price")]
    pub upside_exit_price: f64,
    #[serde(rename = "downside_exit_price")]
    pub downside_exit_price: f64,
    #[serde(rename = "max_slippage", skip_serializing_if = "Option::is_none")]
    pub max_slippage: Option<f64>,
    #[serde(rename = "end_time")]
    pub end_time: f64,
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
}

impl PrivateBotsInlineItemsOneof2 {
    pub fn new(
        bot_id: String,
        status: Status,
        strategy: String,
        instrument_name: String,
        bids: Vec<f64>,
        asks: Vec<f64>,
        step_size: f64,
        base_position: f64,
        upside_exit_price: f64,
        downside_exit_price: f64,
        end_time: f64,
    ) -> PrivateBotsInlineItemsOneof2 {
        PrivateBotsInlineItemsOneof2 {
            bot_id,
            status,
            stop_reason: None,
            strategy,
            instrument_name,
            bids,
            asks,
            step_size,
            base_position,
            upside_exit_price,
            downside_exit_price,
            max_slippage: None,
            end_time,
            label: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "stopped")]
    Stopped,
}

impl Default for Status {
    fn default() -> Status {
        Self::Active
    }
}
