/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.49.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrivateNotificationsInboxInlinePropertiesNotificationsItems {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "time")]
    pub time: f64,
    #[serde(rename = "category")]
    pub category: String,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "display_type")]
    pub display_type: DisplayType,
    #[serde(rename = "read")]
    pub read: bool,
    #[serde(rename = "account_name", skip_serializing_if = "Option::is_none")]
    pub account_name: Option<String>,
    #[serde(rename = "account_number", skip_serializing_if = "Option::is_none")]
    pub account_number: Option<String>,
    #[serde(rename = "popup")]
    pub popup: bool,
}

impl PrivateNotificationsInboxInlinePropertiesNotificationsItems {
    pub fn new(
        id: String,
        time: f64,
        category: String,
        title: String,
        message: String,
        display_type: DisplayType,
        read: bool,
        popup: bool,
    ) -> PrivateNotificationsInboxInlinePropertiesNotificationsItems {
        PrivateNotificationsInboxInlinePropertiesNotificationsItems {
            id,
            time,
            category,
            title,
            message,
            display_type,
            read,
            account_name: None,
            account_number: None,
            popup,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DisplayType {
    #[serde(rename = "success")]
    Success,
    #[serde(rename = "failure")]
    Failure,
    #[serde(rename = "info")]
    Info,
    #[serde(rename = "warning")]
    Warning,
    #[serde(rename = "critical")]
    Critical,
}

impl Default for DisplayType {
    fn default() -> DisplayType {
        Self::Success
    }
}
