/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.49.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrivateRequiredMarginBreakdownInlinePropertiesPortfolioPropertiesUnderlyingsItemsScenariosInnerAssetsInner
{
    #[serde(rename = "asset_name", skip_serializing_if = "Option::is_none")]
    pub asset_name: Option<String>,
    #[serde(rename = "position", skip_serializing_if = "Option::is_none")]
    pub position: Option<f64>,
    #[serde(rename = "underlying_pnl", skip_serializing_if = "Option::is_none")]
    pub underlying_pnl: Option<f64>,
    #[serde(rename = "pnl", skip_serializing_if = "Option::is_none")]
    pub pnl: Option<f64>,
    #[serde(rename = "current_price", skip_serializing_if = "Option::is_none")]
    pub current_price: Option<f64>,
    #[serde(rename = "scenario_price", skip_serializing_if = "Option::is_none")]
    pub scenario_price: Option<f64>,
}

impl PrivateRequiredMarginBreakdownInlinePropertiesPortfolioPropertiesUnderlyingsItemsScenariosInnerAssetsInner {
    pub fn new() -> PrivateRequiredMarginBreakdownInlinePropertiesPortfolioPropertiesUnderlyingsItemsScenariosInnerAssetsInner {
        PrivateRequiredMarginBreakdownInlinePropertiesPortfolioPropertiesUnderlyingsItemsScenariosInnerAssetsInner {
            asset_name: None,
            position: None,
            underlying_pnl: None,
            pnl: None,
            current_price: None,
            scenario_price: None,
        }
    }
}
