/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.49.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrivateBotsInlineItemsOneof1 {
    #[serde(rename = "bot_id")]
    pub bot_id: String,
    #[serde(rename = "status")]
    pub status: Status,
    #[serde(rename = "stop_reason", skip_serializing_if = "Option::is_none")]
    pub stop_reason: Option<String>,
    #[serde(rename = "strategy")]
    pub strategy: String,
    #[serde(rename = "instrument_name")]
    pub instrument_name: String,
    #[serde(rename = "signal")]
    pub signal: Signal,
    #[serde(rename = "bid_offset")]
    pub bid_offset: f64,
    #[serde(rename = "ask_offset")]
    pub ask_offset: f64,
    #[serde(rename = "quote_size")]
    pub quote_size: f64,
    #[serde(rename = "min_position")]
    pub min_position: f64,
    #[serde(rename = "max_position")]
    pub max_position: f64,
    #[serde(rename = "end_time")]
    pub end_time: f64,
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
}

impl PrivateBotsInlineItemsOneof1 {
    pub fn new(
        bot_id: String,
        status: Status,
        strategy: String,
        instrument_name: String,
        signal: Signal,
        bid_offset: f64,
        ask_offset: f64,
        quote_size: f64,
        min_position: f64,
        max_position: f64,
        end_time: f64,
    ) -> PrivateBotsInlineItemsOneof1 {
        PrivateBotsInlineItemsOneof1 {
            bot_id,
            status,
            stop_reason: None,
            strategy,
            instrument_name,
            signal,
            bid_offset,
            ask_offset,
            quote_size,
            min_position,
            max_position,
            end_time,
            label: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "stopped")]
    Stopped,
}

impl Default for Status {
    fn default() -> Status {
        Self::Active
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Signal {
    #[serde(rename = "index")]
    Index,
    #[serde(rename = "mark")]
    Mark,
}

impl Default for Signal {
    fn default() -> Signal {
        Self::Index
    }
}
