/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.49.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrivateRequiredMarginBreakdownInlinePropertiesPortfolioPropertiesUnderlyingsItemsPropertiesScenariosItemsPro
{
    #[serde(rename = "instrument_name", skip_serializing_if = "Option::is_none")]
    pub instrument_name: Option<String>,
    #[serde(rename = "position", skip_serializing_if = "Option::is_none")]
    pub position: Option<f64>,
    #[serde(rename = "instrument_pnl", skip_serializing_if = "Option::is_none")]
    pub instrument_pnl: Option<f64>,
    #[serde(rename = "pnl", skip_serializing_if = "Option::is_none")]
    pub pnl: Option<f64>,
    #[serde(rename = "current_price", skip_serializing_if = "Option::is_none")]
    pub current_price: Option<f64>,
    #[serde(rename = "scenario_price", skip_serializing_if = "Option::is_none")]
    pub scenario_price: Option<f64>,
    #[serde(rename = "open_order", skip_serializing_if = "Option::is_none")]
    pub open_order: Option<bool>,
    #[serde(rename = "assumed_filled", skip_serializing_if = "Option::is_none")]
    pub assumed_filled: Option<bool>,
}

impl PrivateRequiredMarginBreakdownInlinePropertiesPortfolioPropertiesUnderlyingsItemsPropertiesScenariosItemsPro {
    pub fn new() -> PrivateRequiredMarginBreakdownInlinePropertiesPortfolioPropertiesUnderlyingsItemsPropertiesScenariosItemsPro {
        PrivateRequiredMarginBreakdownInlinePropertiesPortfolioPropertiesUnderlyingsItemsPropertiesScenariosItemsPro {
            instrument_name: None,
            position: None,
            instrument_pnl: None,
            pnl: None,
            current_price: None,
            scenario_price: None,
            open_order: None,
            assumed_filled: None,
        }
    }
}
