/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.49.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrivateRequiredMarginBreakdownInlinePropertiesPortfolioPropertiesUnderlyingsItems {
    #[serde(rename = "underlying", skip_serializing_if = "Option::is_none")]
    pub underlying: Option<String>,
    #[serde(rename = "required_margin", skip_serializing_if = "Option::is_none")]
    pub required_margin: Option<f64>,
    #[serde(rename = "scenario_margin", skip_serializing_if = "Option::is_none")]
    pub scenario_margin: Option<f64>,
    #[serde(rename = "loss_margin", skip_serializing_if = "Option::is_none")]
    pub loss_margin: Option<f64>,
    #[serde(rename = "d1_roll_cash_position", skip_serializing_if = "Option::is_none")]
    pub d1_roll_cash_position: Option<f64>,
    #[serde(rename = "options_roll_cash_position", skip_serializing_if = "Option::is_none")]
    pub options_roll_cash_position: Option<f64>,
    #[serde(rename = "roll_cash_position", skip_serializing_if = "Option::is_none")]
    pub roll_cash_position: Option<f64>,
    #[serde(rename = "d1_roll_contingency_margin", skip_serializing_if = "Option::is_none")]
    pub d1_roll_contingency_margin: Option<f64>,
    #[serde(rename = "options_roll_contingency_margin", skip_serializing_if = "Option::is_none")]
    pub options_roll_contingency_margin: Option<f64>,
    #[serde(rename = "roll_contingency_margin", skip_serializing_if = "Option::is_none")]
    pub roll_contingency_margin: Option<f64>,
    #[serde(rename = "options_short_cash_position", skip_serializing_if = "Option::is_none")]
    pub options_short_cash_position: Option<f64>,
    #[serde(rename = "options_contingency_margin", skip_serializing_if = "Option::is_none")]
    pub options_contingency_margin: Option<f64>,
    #[serde(rename = "scenario_used", skip_serializing_if = "Option::is_none")]
    pub scenario_used: Option<i32>,
    #[serde(rename = "scenarios", skip_serializing_if = "Option::is_none")]
    pub scenarios: Option<Vec<models::PrivateRequiredMarginBreakdownInlinePropertiesPortfolioPropertiesUnderlyingsItemsScenariosInner>>,
}

impl PrivateRequiredMarginBreakdownInlinePropertiesPortfolioPropertiesUnderlyingsItems {
    pub fn new() -> PrivateRequiredMarginBreakdownInlinePropertiesPortfolioPropertiesUnderlyingsItems
    {
        PrivateRequiredMarginBreakdownInlinePropertiesPortfolioPropertiesUnderlyingsItems {
            underlying: None,
            required_margin: None,
            scenario_margin: None,
            loss_margin: None,
            d1_roll_cash_position: None,
            options_roll_cash_position: None,
            roll_cash_position: None,
            d1_roll_contingency_margin: None,
            options_roll_contingency_margin: None,
            roll_contingency_margin: None,
            options_short_cash_position: None,
            options_contingency_margin: None,
            scenario_used: None,
            scenarios: None,
        }
    }
}
