/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.49.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublicAllInstrumentsInlineItemsPropertiesLegsItems {
    #[serde(rename = "instrument_name", skip_serializing_if = "Option::is_none")]
    pub instrument_name: Option<String>,
    #[serde(rename = "quantity", skip_serializing_if = "Option::is_none")]
    pub quantity: Option<i32>,
}

impl PublicAllInstrumentsInlineItemsPropertiesLegsItems {
    pub fn new() -> PublicAllInstrumentsInlineItemsPropertiesLegsItems {
        PublicAllInstrumentsInlineItemsPropertiesLegsItems {
            instrument_name: None,
            quantity: None,
        }
    }
}
