/*
 * Websocket Subscription Schemas
 *
 * Schema definitions Websocket API subscriptions for Thalex exchange.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RecentTradesNotification {
    /// Channel name as in subscription.
    #[serde(rename = "channel_name")]
    pub channel_name: ChannelName,
    #[serde(rename = "notification")]
    pub notification: models::RecentTrades,
}

impl RecentTradesNotification {
    pub fn new(
        channel_name: ChannelName,
        notification: models::RecentTrades,
    ) -> RecentTradesNotification {
        RecentTradesNotification {
            channel_name,
            notification,
        }
    }
}
/// Channel name as in subscription.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ChannelName {
    #[serde(rename = "recent_trades.<target>.<category>")]
    RecentTradesPeriodLessThanTargetGreaterThanPeriodLessThanCategoryGreaterThan,
}

impl Default for ChannelName {
    fn default() -> ChannelName {
        Self::RecentTradesPeriodLessThanTargetGreaterThanPeriodLessThanCategoryGreaterThan
    }
}
