/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.49.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RestPrivateVerifyInternalTransferRequestAssetsInner {
    /// Asset name
    #[serde(rename = "asset_name")]
    pub asset_name: String,
    /// Amount to transfer. Use a negative value to transfer in reverse direction.
    #[serde(rename = "amount")]
    pub amount: f64,
}

impl RestPrivateVerifyInternalTransferRequestAssetsInner {
    pub fn new(asset_name: String, amount: f64) -> RestPrivateVerifyInternalTransferRequestAssetsInner {
        RestPrivateVerifyInternalTransferRequestAssetsInner {
            asset_name,
            amount,
        }
    }
}

