/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.49.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RestPrivateDailyMarkHistory200Response {
    Success13(Box<models::Success13>),
    ErrorResponse(Box<models::ErrorResponse>),
}

impl Default for RestPrivateDailyMarkHistory200Response {
    fn default() -> Self {
        Self::Success13(Default::default())
    }
}

