/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.49.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RestPrivateSell200Response {
    Success1(Box<models::Success1>),
    ErrorResponse(Box<models::ErrorResponse>),
}

impl Default for RestPrivateSell200Response {
    fn default() -> Self {
        Self::Success1(Default::default())
    }
}

