/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.49.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RestPrivateCreateRfqRequestLegsInner {
    /// The leg instrument. Must be an outright instrument, not a combination.
    #[serde(rename = "instrument_name")]
    pub instrument_name: String,
    /// Amount to trade for this leg. Negative for short.
    #[serde(rename = "amount")]
    pub amount: f64,
}

impl RestPrivateCreateRfqRequestLegsInner {
    pub fn new(instrument_name: String, amount: f64) -> RestPrivateCreateRfqRequestLegsInner {
        RestPrivateCreateRfqRequestLegsInner {
            instrument_name,
            amount,
        }
    }
}

