/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.49.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RestPrivateTradeRfqRequest {
    /// The ID of the RFQ
    #[serde(rename = "rfq_id")]
    pub rfq_id: String,
    /// Whether to buy or sell. *Important*: this relates to the combination as created by the system, *not* the package as originally requested (although they should be equal). 
    #[serde(rename = "direction")]
    pub direction: Direction,
    /// The maximum (for buy) or minimum (for sell) price to trade at. This is the price for one combination, not for the entire package. 
    #[serde(rename = "limit_price")]
    pub limit_price: f64,
}

impl RestPrivateTradeRfqRequest {
    pub fn new(rfq_id: String, direction: Direction, limit_price: f64) -> RestPrivateTradeRfqRequest {
        RestPrivateTradeRfqRequest {
            rfq_id,
            direction,
            limit_price,
        }
    }
}
/// Whether to buy or sell. *Important*: this relates to the combination as created by the system, *not* the package as originally requested (although they should be equal). 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Direction {
    #[serde(rename = "buy")]
    Buy,
    #[serde(rename = "sell")]
    Sell,
}

impl Default for Direction {
    fn default() -> Direction {
        Self::Buy
    }
}

