/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.49.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RestPrivateCancelRequest {
    /// Exactly one of `client_order_id` or `order_id` must be specified.
    #[serde(rename = "client_order_id", skip_serializing_if = "Option::is_none")]
    pub client_order_id: Option<i32>,
    /// Exactly one of `client_order_id` or `order_id` must be specified.
    #[serde(rename = "order_id", skip_serializing_if = "Option::is_none")]
    pub order_id: Option<String>,
}

impl RestPrivateCancelRequest {
    pub fn new() -> RestPrivateCancelRequest {
        RestPrivateCancelRequest {
            client_order_id: None,
            order_id: None,
        }
    }
}

