/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.49.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RestPrivateCreateRfqRequest {
    /// Specify any number of legs that you'd like to trade in a single package. Leg amounts may be positive (long) or negative (short), and must adhere to the regular volume tick size for the respective instrument. At least one leg must be long. 
    #[serde(rename = "legs")]
    pub legs: Vec<models::RestPrivateCreateRfqRequestLegsInner>,
    /// User label for this RFQ, which will be reflected in eventual trades.
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
}

impl RestPrivateCreateRfqRequest {
    pub fn new(legs: Vec<models::RestPrivateCreateRfqRequestLegsInner>) -> RestPrivateCreateRfqRequest {
        RestPrivateCreateRfqRequest {
            legs,
            label: None,
        }
    }
}

