/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.49.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RestPublicTicker200Response {
    Success29(Box<models::Success29>),
    ErrorResponse(Box<models::ErrorResponse>),
}

impl Default for RestPublicTicker200Response {
    fn default() -> Self {
        Self::Success29(Default::default())
    }
}

