/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.49.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RestPrivateVerifyInternalTransferRequest {
    /// Destination account number.
    #[serde(rename = "destination_account_number")]
    pub destination_account_number: String,
    #[serde(rename = "assets", skip_serializing_if = "Option::is_none")]
    pub assets: Option<Vec<models::RestPrivateVerifyInternalTransferRequestAssetsInner>>,
    #[serde(rename = "positions", skip_serializing_if = "Option::is_none")]
    pub positions: Option<Vec<models::RestPrivateVerifyInternalTransferRequestPositionsInner>>,
}

impl RestPrivateVerifyInternalTransferRequest {
    pub fn new(destination_account_number: String) -> RestPrivateVerifyInternalTransferRequest {
        RestPrivateVerifyInternalTransferRequest {
            destination_account_number,
            assets: None,
            positions: None,
        }
    }
}

