/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.49.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Success4 {
    /// The number of orders successfully deleted.
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<f64>,
}

impl Success4 {
    pub fn new() -> Success4 {
        Success4 {
            result: None,
        }
    }
}

