/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.49.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Success5 {
    /// List of conditional orders, both active and formerly active. After activation, conditional orders may be listed for another few days. 
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<Vec<models::ConditionalOrder>>,
}

impl Success5 {
    pub fn new() -> Success5 {
        Success5 {
            result: None,
        }
    }
}

