/*
 * Thalex API Description
 *
 * Talex API documentation
 *
 * The version of the OpenAPI document: 2.49.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Success7 {
    /// List of bots, both active and formerly active. Bots may be listed for another few days after they're stopped. 
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<Vec<models::Bot>>,
}

impl Success7 {
    pub fn new() -> Success7 {
        Success7 {
            result: None,
        }
    }
}

