/*
 * Websocket Subscription Schemas
 *
 * Schema definitions Websocket API subscriptions for Thalex exchange.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TickerNotification {
    /// Channel name as in subscription.
    #[serde(rename = "channel_name")]
    pub channel_name: ChannelName,
    /// Channel-specific content
    #[serde(rename = "notification")]
    pub notification: models::Ticker,
}

impl TickerNotification {
    pub fn new(channel_name: ChannelName, notification: models::Ticker) -> TickerNotification {
        TickerNotification {
            channel_name,
            notification,
        }
    }
}
/// Channel name as in subscription.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ChannelName {
    #[serde(rename = "ticker.<instrument>.<delay>")]
    TickerPeriodLessThanInstrumentGreaterThanPeriodLessThanDelayGreaterThan,
}

impl Default for ChannelName {
    fn default() -> ChannelName {
        Self::TickerPeriodLessThanInstrumentGreaterThanPeriodLessThanDelayGreaterThan
    }
}
