/*
 * Thalex RPC API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TopOfBookPerpetual : Top of book data, null for resolutions other than 1 minute
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TopOfBookPerpetual {
    /// Top bid price, or null if bid order book is empty
    #[serde(rename = "bidPrice", deserialize_with = "Option::deserialize")]
    pub bid_price: Option<f64>,
    /// Top bid size, or null if bid order book is empty
    #[serde(rename = "bidSize", deserialize_with = "Option::deserialize")]
    pub bid_size: Option<f64>,
    /// Top ask price, or null if ask order book is empty
    #[serde(rename = "askPrice", deserialize_with = "Option::deserialize")]
    pub ask_price: Option<f64>,
    /// Top ask size, or null if ask order book is empty
    #[serde(rename = "askSize", deserialize_with = "Option::deserialize")]
    pub ask_size: Option<f64>,
}

impl TopOfBookPerpetual {
    /// Top of book data, null for resolutions other than 1 minute
    pub fn new(
        bid_price: Option<f64>,
        bid_size: Option<f64>,
        ask_price: Option<f64>,
        ask_size: Option<f64>,
    ) -> TopOfBookPerpetual {
        TopOfBookPerpetual {
            bid_price,
            bid_size,
            ask_price,
            ask_size,
        }
    }
}
