/*
 * Thalex RPC API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UnsubscribeParams {
    /// List of channels to unsubscribe from.  and private channels may be mixed.
    #[serde(rename = "channels")]
    pub channels: Vec<String>,
}

impl UnsubscribeParams {
    pub fn new(channels: Vec<String>) -> UnsubscribeParams {
        UnsubscribeParams { channels }
    }
}
